---
kind: pipeline
name: commitlint
steps:
- name: npm install
  image: &node_image node:10.16.0-alpine
  commands:
  - npm i
- name: tag/commitlint
  image: *node_image
  commands:
  - npx commitlint --from HEAD~1 --to HEAD
  when:
    event:
    - tag
    - push
- name: pr/commitlint
  image: *node_image
  commands:
  - npx commitlint --from master --to HEAD || exit 1
  when:
    event:
    - pull_request
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: download go modules
  image: &image_go golang:1.13.4
  commands:
  - go mod download
  environment:
    GOPATH: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.26.0-alpine
  commands:
  - golangci-lint run
  environment:
    GOPATH: /go
  volumes: *volumes
- name: codecov
  image: *image_go
  commands:
  # bash and cgo seem to be required
  - bash scripts/codecov-test.sh
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - test "$LOCAL" = "true" -o "$DRONE_BUILD_EVENT" = "pull_request" || bash /tmp/codecov.sh
  environment:
    GOPATH: /go
    CODECOV_TOKEN:
      from_secret: codecov_token
- name: remove changes
  image: &image_git plugins/git
  commands:
  # Sometimes it is failed to release by goreleaser due to changes of go.sum
  - git checkout -- .

- name: fetch tags to release
  image: *image_git
  commands:
  - git fetch --tags
  when:
    event:
    - tag
- name: release
  image: &goreleaser goreleaser/goreleaser:v0.123.3
  commands:
  - goreleaser release
  environment:
    GOPATH: /go
    GITHUB_TOKEN:
      from_secret: github_token
  volumes: *volumes
  when:
    event:
    - tag

- name: create a dummy tag to test releasing
  image: *image_git
  commands:
  - git tag v0.1.0-alpha
  when:
    event:
    - pull_request
    - push
- name: release (skip publish)
  image: *goreleaser
  commands:
  - goreleaser release --skip-publish
  environment:
    GOPATH: /go
  volumes: *volumes
  when:
    event:
    - pull_request
    - push
